language: java
sudo: false # faster builds
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V
script:
- mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura coveralls:cobertura
  - mvn clean site -X